### ISSUE TITLE
composer need to be update

### ISSUE THREAD

**Issue by cansozeri** [illuminate/encryption#2]
I think composer needs to be update with => "illuminate/support": "5.2.*"

**Comment by GrahamCampbell** [comment]
Please close this.

**Comment by cansozeri** [comment]
Sorry why ? Am I wrong about this,

I am using laravel components and I can not use laravel 5.2 components because of this, you have updated it to 5.2 in laravel core, but here it's is still 5.1. I have got a composer error because of this, I had to installed it manually ... 

Here is the error message : 

```
illuminate/encryption 5.2.x-dev requires illuminate/support 5.1.* -> satisfiable by illuminate/support[5.1.x-dev].
```

And my composer require part : 

```
        "illuminate/contracts": "5.2.*@dev",
        "illuminate/support": "5.2.*@dev",
        "illuminate/container": "5.2.*@dev",
        "illuminate/routing": "5.2.*@dev",
        "illuminate/events": "5.2.*@dev",
        "illuminate/encryption": "5.2.*@dev",
        "illuminate/cookie": "5.2.*@dev",
        "illuminate/auth": "5.2.*@dev",
        "illuminate/hashing": "5.2.*@dev",
        "guzzlehttp/guzzle": "~6.0",
	"illuminate/config": "5.2.*@dev",
        "illuminate/cache": "5.2.*@dev",
        "illuminate/redis": "5.2.*@dev",
        "illuminate/pagination":"5.2.*@dev",
```

If I remove the encryption package, the problem is gone ...

**Comment by GrahamCampbell** [comment]
Issues are meant to be disabled on this repo.

**Comment by cansozeri** [comment]
But where can I ask for this ??? And how can it be fixed ?

**Comment by GrahamCampbell** [comment]
Also, you really shouldn't be using Laravel 5.2 yet. There will be zero support for it.

**Comment by GrahamCampbell** [comment]
This will be fixed in about 2 hours time when the next split job runs.

**Comment by GrahamCampbell** [comment]
I've fixed it in laravel/framework. https://github.com/laravel/framework/commit/fe8d82648e629be1cb0b66e401f7a406139eecbf

**Comment by cansozeri** [comment]
Ok thanx : )

**Comment by GrahamCampbell** [comment]
Please close the PR too.
