### ISSUE TITLE
Interoperability concerns?

### ISSUE THREAD

**Issue by drowe** [illuminate/encryption#4]
The 'encrypt' method serializes data using PHP serialization, with the corresponding 'decrypt' method doing the unserialization.

Is there no expectation if interoperability with platforms outside of Laravel / PHP?  Why should a client receiving encrypted data be required to implement PHP unserialization?

**Comment by Potherca** [comment]
I have the same question as the OP. Can I get a response here? Or do I need to open a new issue to ask the same question? (Or in a different location?)
